version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
